### ISSUE TITLE
Mapbox GL

### ISSUE THREAD

**Issue by benstadin** [kartotherian/kartotherian-server#1]
Is there a chance that mapbox-gl-js will return? I saw that it was included in earlier versions, wasn't it working well?

~Ben

**Comment by nyurik** [comment]
Absolutelly!  Technically you can already use it - by setting up your own labs instance with the fonts and js libs, and pointing it to the maps.wikimedia.org PBF files. We simply haven't had enough time to work on it, but patches are welcome :))

We need:
- a well documented way to generate font PBF files (IIRC, we need to use [node-fontnik](https://github.com/mapbox/node-fontnik) or another Mapbox script)
- Adapt [Mapbox's GL style](https://github.com/mapbox/mapbox-gl-styles/tree/master/styles) to use our tileset
- evaluate if we have any large tiles (e.g. above 500kb for now), and reduce their size

**Comment by nyurik** [comment]
This issue was moved to kartotherian/kartotherian#18
